### ISSUE TITLE
Framework Installtion and testing

### ISSUE THREAD

**Issue by dai-dao** [xuefengchang/micros_swarm_framework-release#1]
Hi,

Could you give me some tips on how to correctly install and run the examples in this framework?

I have successfully installed with 'sudo make install', but I can't run the examples in the 'apps' folder. Seems like it depends on OpenSplice DDS header files. Do I have to install OpenSplice DDS and set the appropriate header paths in order to run these examples?

Thanks

**Comment by xuefengchang** [comment]
Hi, 
Thanks for your attention! If you want to use or test this framework, the first thing you have to do is installing the ROS indigo version. you can follow this page: http://wiki.ros.org/indigo/Installation/Ubuntu
You may also need to install the stage-ros package by sudo apt-get install ros-indigo-stage-ros

When you installed ROS successfully, you can install the framework by the command: sudo apt-get install ros-indigo-micros-swarm-framework in the termminal directly, or download the source code from the following page: https://github.com/xuefengchang/micros_swarm_framework ,and compile in your catkin workspace by yourself (recommend). Then, you could run these examples.

This framework use ROS publish/subscribe communication mechanism default. If you installed opensplice dds successfully you can also change the communication mechanism by modifying the Cmake file. you just need to set the "USE_ROS" option OFF and set the "USE_OPENSPLICE_DDS" option ON in the cmake file and then recompile.

You can following this page to install opensplice dds: 
http://www.prismtech.com/dds-community/software-downloads/installing

**Comment by dai-dao** [comment]
Thanks for the quick reply. Everything is successfully installed and tested. Although I installed on ROS Kinetic, Ubuntu 16.04.

Cheers
